In [1]:
import numpy as np

In [5]:
"""
    P is the probability distribution of our believe of localization
    in the world
"""
P = np.array([0.2, 0.2, 0.2, 0.2, 0.2])

world = ['green', 'red', 'red', 'green', 'green']

pHit, pMiss = 0.6, 0.2

In [35]:
def sense(p, z):
    q = np.zeros_like(p)
    
    for i in range(p.shape[0]):
        hit = (z == world[i])
        q[i] = p[i] * (hit * pHit + (1-hit) * pMiss)
        
    q /= q.sum()
    return q

In [42]:
# The robots senses a he's in a 'green' place
Z = 'red'
print(sense(P, Z))

[0.11111111 0.33333333 0.33333333 0.11111111 0.11111111]


In [54]:
def multi_sens(p, z):
    q = p.copy()
    
    for measurement in z:
        q = sense(q, measurement)
    return q

In [55]:
Z = ['red', 'green']
print(multi_sens(P, Z))

[0.2 0.2 0.2 0.2 0.2]


In [68]:
def move(p, u):
    u = u % p.shape[0]
    # put the last u elements in front of the others
    return np.concatenate((p[-u:], p[:-u]))

In [69]:
P = np.array([0, 1, 0, 0, 0])
print(move(P, 2))

[0 0 0 1 0]
